### YamlMime:ManagedReference
items:
- uid: Global.BaseConfigItem
  commentId: T:Global.BaseConfigItem
  id: BaseConfigItem
  parent: Global
  children:
  - Global.BaseConfigItem.description
  - Global.BaseConfigItem.name
  - Global.BaseConfigItem.remark
  langs:
  - csharp
  - vb
  name: BaseConfigItem
  nameWithType: BaseConfigItem
  fullName: BaseConfigItem
  type: Class
  source:
    remote:
      path: Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
      branch: master
      repo: https://github.com/iiaa22/53-Unity.git
    id: BaseConfigItem
    path: ../Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
    startLine: 43
  assemblies:
  - Assembly-CSharp
  namespace: Global
  syntax:
    content: >-
      [Serializable]

      public abstract class BaseConfigItem
    content.vb: >-
      <Serializable>

      Public MustInherit Class BaseConfigItem
  inheritance:
  - System.Object
  derivedClasses:
  - Global.LanguageConfigItem
  - Global.PlatformCommonConfigItem
  - Global.SkillsConfigItem
  - Global.StatesConfigItem
  - Global.UnitsConfigItem
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: Global.BaseConfigItem.name
  commentId: F:Global.BaseConfigItem.name
  id: name
  parent: Global.BaseConfigItem
  langs:
  - csharp
  - vb
  name: name
  nameWithType: BaseConfigItem.name
  fullName: BaseConfigItem.name
  type: Field
  source:
    remote:
      path: Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
      branch: master
      repo: https://github.com/iiaa22/53-Unity.git
    id: name
    path: ../Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
    startLine: 47
  assemblies:
  - Assembly-CSharp
  namespace: Global
  syntax:
    content: >-
      [Tooltip("名称")]

      public string name
    return:
      type: System.String
    content.vb: >-
      <Tooltip("名称")>

      Public name As String
  attributes:
  - type: UnityEngine.TooltipAttribute
    ctor: UnityEngine.TooltipAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: 名称
- uid: Global.BaseConfigItem.description
  commentId: F:Global.BaseConfigItem.description
  id: description
  parent: Global.BaseConfigItem
  langs:
  - csharp
  - vb
  name: description
  nameWithType: BaseConfigItem.description
  fullName: BaseConfigItem.description
  type: Field
  source:
    remote:
      path: Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
      branch: master
      repo: https://github.com/iiaa22/53-Unity.git
    id: description
    path: ../Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
    startLine: 50
  assemblies:
  - Assembly-CSharp
  namespace: Global
  syntax:
    content: >-
      [TextArea]

      [Tooltip("描述")]

      public string description
    return:
      type: System.String
    content.vb: >-
      <TextArea>

      <Tooltip("描述")>

      Public description As String
  attributes:
  - type: UnityEngine.TextAreaAttribute
    ctor: UnityEngine.TextAreaAttribute.#ctor
    arguments: []
  - type: UnityEngine.TooltipAttribute
    ctor: UnityEngine.TooltipAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: 描述
- uid: Global.BaseConfigItem.remark
  commentId: F:Global.BaseConfigItem.remark
  id: remark
  parent: Global.BaseConfigItem
  langs:
  - csharp
  - vb
  name: remark
  nameWithType: BaseConfigItem.remark
  fullName: BaseConfigItem.remark
  type: Field
  source:
    remote:
      path: Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
      branch: master
      repo: https://github.com/iiaa22/53-Unity.git
    id: remark
    path: ../Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
    startLine: 53
  assemblies:
  - Assembly-CSharp
  namespace: Global
  syntax:
    content: >-
      [TextArea]

      [Tooltip("备注")]

      public string remark
    return:
      type: System.String
    content.vb: >-
      <TextArea>

      <Tooltip("备注")>

      Public remark As String
  attributes:
  - type: UnityEngine.TextAreaAttribute
    ctor: UnityEngine.TextAreaAttribute.#ctor
    arguments: []
  - type: UnityEngine.TooltipAttribute
    ctor: UnityEngine.TooltipAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: 备注
references:
- uid: Global
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
