### YamlMime:ManagedReference
items:
- uid: Global.BaseConfig`1
  commentId: T:Global.BaseConfig`1
  id: BaseConfig`1
  parent: Global
  children:
  - Global.BaseConfig`1.DataCount
  - Global.BaseConfig`1.Item(System.Int32)
  - Global.BaseConfig`1.Item(System.String)
  - Global.BaseConfig`1.dataList
  - Global.BaseConfig`1.enableConsole
  - Global.BaseConfig`1.version
  langs:
  - csharp
  - vb
  name: BaseConfig<T>
  nameWithType: BaseConfig<T>
  fullName: BaseConfig<T>
  type: Class
  source:
    remote:
      path: Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
      branch: master
      repo: https://github.com/iiaa22/53-Unity.git
    id: BaseConfig
    path: ../Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
    startLine: 8
  assemblies:
  - Assembly-CSharp
  namespace: Global
  summary: 所有配置表的父类
  example: []
  syntax:
    content: 'public abstract class BaseConfig<T> : ScriptableObject where T : BaseConfigItem'
    typeParameters:
    - id: T
      description: 配置数据类型
    content.vb: Public MustInherit Class BaseConfig(Of T As BaseConfigItem) Inherits ScriptableObject
  inheritance:
  - System.Object
  - UnityEngine.Object
  - UnityEngine.ScriptableObject
  derivedClasses:
  - Global.LanguageConfig
  - Global.PlatformCommonConfig
  - Global.SkillsConfig
  - Global.StatesConfig
  - Global.UnitsConfig
  nameWithType.vb: BaseConfig(Of T)
  fullName.vb: BaseConfig(Of T)
  name.vb: BaseConfig(Of T)
- uid: Global.BaseConfig`1.version
  commentId: F:Global.BaseConfig`1.version
  id: version
  parent: Global.BaseConfig`1
  langs:
  - csharp
  - vb
  name: version
  nameWithType: BaseConfig<T>.version
  fullName: BaseConfig<T>.version
  type: Field
  source:
    remote:
      path: Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
      branch: master
      repo: https://github.com/iiaa22/53-Unity.git
    id: version
    path: ../Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
    startLine: 10
  assemblies:
  - Assembly-CSharp
  namespace: Global
  syntax:
    content: public int version
    return:
      type: System.Int32
    content.vb: Public version As Integer
  nameWithType.vb: BaseConfig(Of T).version
  fullName.vb: BaseConfig(Of T).version
- uid: Global.BaseConfig`1.enableConsole
  commentId: F:Global.BaseConfig`1.enableConsole
  id: enableConsole
  parent: Global.BaseConfig`1
  langs:
  - csharp
  - vb
  name: enableConsole
  nameWithType: BaseConfig<T>.enableConsole
  fullName: BaseConfig<T>.enableConsole
  type: Field
  source:
    remote:
      path: Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
      branch: master
      repo: https://github.com/iiaa22/53-Unity.git
    id: enableConsole
    path: ../Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
    startLine: 11
  assemblies:
  - Assembly-CSharp
  namespace: Global
  syntax:
    content: public bool enableConsole
    return:
      type: System.Boolean
    content.vb: Public enableConsole As Boolean
  nameWithType.vb: BaseConfig(Of T).enableConsole
  fullName.vb: BaseConfig(Of T).enableConsole
- uid: Global.BaseConfig`1.dataList
  commentId: F:Global.BaseConfig`1.dataList
  id: dataList
  parent: Global.BaseConfig`1
  langs:
  - csharp
  - vb
  name: dataList
  nameWithType: BaseConfig<T>.dataList
  fullName: BaseConfig<T>.dataList
  type: Field
  source:
    remote:
      path: Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
      branch: master
      repo: https://github.com/iiaa22/53-Unity.git
    id: dataList
    path: ../Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
    startLine: 12
  assemblies:
  - Assembly-CSharp
  namespace: Global
  syntax:
    content: public List<T> dataList
    return:
      type: System.Collections.Generic.List{{T}}
    content.vb: Public dataList As List(Of T)
  nameWithType.vb: BaseConfig(Of T).dataList
  fullName.vb: BaseConfig(Of T).dataList
- uid: Global.BaseConfig`1.Item(System.Int32)
  commentId: P:Global.BaseConfig`1.Item(System.Int32)
  id: Item(System.Int32)
  parent: Global.BaseConfig`1
  langs:
  - csharp
  - vb
  name: this[int]
  nameWithType: BaseConfig<T>.this[int]
  fullName: BaseConfig<T>.this[int]
  type: Property
  source:
    remote:
      path: Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
      branch: master
      repo: https://github.com/iiaa22/53-Unity.git
    id: this[]
    path: ../Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
    startLine: 14
  assemblies:
  - Assembly-CSharp
  namespace: Global
  syntax:
    content: public T this[int id] { get; }
    parameters:
    - id: id
      type: System.Int32
    return:
      type: '{T}'
    content.vb: Public ReadOnly Default Property this[](id As Integer) As T
  overload: Global.BaseConfig`1.Item*
  nameWithType.vb: BaseConfig(Of T).this[](Integer)
  fullName.vb: BaseConfig(Of T).this[](Integer)
  name.vb: this[](Integer)
- uid: Global.BaseConfig`1.Item(System.String)
  commentId: P:Global.BaseConfig`1.Item(System.String)
  id: Item(System.String)
  parent: Global.BaseConfig`1
  langs:
  - csharp
  - vb
  name: this[string]
  nameWithType: BaseConfig<T>.this[string]
  fullName: BaseConfig<T>.this[string]
  type: Property
  source:
    remote:
      path: Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
      branch: master
      repo: https://github.com/iiaa22/53-Unity.git
    id: this[]
    path: ../Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
    startLine: 27
  assemblies:
  - Assembly-CSharp
  namespace: Global
  syntax:
    content: public T this[string name] { get; }
    parameters:
    - id: name
      type: System.String
    return:
      type: '{T}'
    content.vb: Public ReadOnly Default Property this[](name As String) As T
  overload: Global.BaseConfig`1.Item*
  nameWithType.vb: BaseConfig(Of T).this[](String)
  fullName.vb: BaseConfig(Of T).this[](String)
  name.vb: this[](String)
- uid: Global.BaseConfig`1.DataCount
  commentId: P:Global.BaseConfig`1.DataCount
  id: DataCount
  parent: Global.BaseConfig`1
  langs:
  - csharp
  - vb
  name: DataCount
  nameWithType: BaseConfig<T>.DataCount
  fullName: BaseConfig<T>.DataCount
  type: Property
  source:
    remote:
      path: Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
      branch: master
      repo: https://github.com/iiaa22/53-Unity.git
    id: DataCount
    path: ../Assets/YoJiaFrameWork/Scripts/Base/BaseConfig.cs
    startLine: 40
  assemblies:
  - Assembly-CSharp
  namespace: Global
  syntax:
    content: public int DataCount { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property DataCount As Integer
  overload: Global.BaseConfig`1.DataCount*
  nameWithType.vb: BaseConfig(Of T).DataCount
  fullName.vb: BaseConfig(Of T).DataCount
references:
- uid: Global
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: UnityEngine.Object
  commentId: T:UnityEngine.Object
  parent: UnityEngine
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: UnityEngine.Object
- uid: UnityEngine.ScriptableObject
  commentId: T:UnityEngine.ScriptableObject
  parent: UnityEngine
  isExternal: true
  name: ScriptableObject
  nameWithType: ScriptableObject
  fullName: UnityEngine.ScriptableObject
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System.Collections.Generic.List{{T}}
  commentId: T:System.Collections.Generic.List{`0}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Global.BaseConfig`1.Item*
  commentId: Overload:Global.BaseConfig`1.Item
  href: Global.BaseConfig-1.html#BaseConfig_1_Item_System_Int32_
  name: this
  nameWithType: BaseConfig<T>.this
  fullName: BaseConfig<T>.this
  nameWithType.vb: BaseConfig(Of T).this[]
  fullName.vb: BaseConfig(Of T).this[]
  name.vb: this[]
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Global.BaseConfig`1.DataCount*
  commentId: Overload:Global.BaseConfig`1.DataCount
  href: Global.BaseConfig-1.html#BaseConfig_1_DataCount
  name: DataCount
  nameWithType: BaseConfig<T>.DataCount
  fullName: BaseConfig<T>.DataCount
  nameWithType.vb: BaseConfig(Of T).DataCount
  fullName.vb: BaseConfig(Of T).DataCount
