### YamlMime:ManagedReference
items:
- uid: Global.LanguageConfig
  commentId: T:Global.LanguageConfig
  id: LanguageConfig
  parent: Global
  children: []
  langs:
  - csharp
  - vb
  name: LanguageConfig
  nameWithType: LanguageConfig
  fullName: LanguageConfig
  type: Class
  source:
    remote:
      path: Assets/YoJiaFrameWork/Scripts/Config/LanguageConfig.cs
      branch: master
      repo: https://github.com/iiaa22/53-Unity.git
    id: LanguageConfig
    path: ../Assets/YoJiaFrameWork/Scripts/Config/LanguageConfig.cs
    startLine: 4
  assemblies:
  - Assembly-CSharp
  namespace: Global
  syntax:
    content: >-
      [CreateAssetMenu(fileName = "New LanguageConfig", menuName = "YoJiaFrameWork配置/语言配置列表", order = 0)]

      public class LanguageConfig : BaseConfig<LanguageConfigItem>
    content.vb: >-
      <CreateAssetMenu(fileName:="New LanguageConfig", menuName:="YoJiaFrameWork配置/语言配置列表", order:=0)>

      Public Class LanguageConfig Inherits BaseConfig(Of LanguageConfigItem)
  inheritance:
  - System.Object
  - UnityEngine.Object
  - UnityEngine.ScriptableObject
  - Global.BaseConfig{LanguageConfigItem}
  inheritedMembers:
  - Global.BaseConfig{LanguageConfigItem}.version
  - Global.BaseConfig{LanguageConfigItem}.enableConsole
  - Global.BaseConfig{LanguageConfigItem}.dataList
  - Global.BaseConfig{LanguageConfigItem}.Item(System.Int32)
  - Global.BaseConfig{LanguageConfigItem}.Item(System.String)
  - Global.BaseConfig{LanguageConfigItem}.DataCount
  attributes:
  - type: UnityEngine.CreateAssetMenuAttribute
    ctor: UnityEngine.CreateAssetMenuAttribute.#ctor
    arguments: []
    namedArguments:
    - name: fileName
      type: System.String
      value: New LanguageConfig
    - name: menuName
      type: System.String
      value: YoJiaFrameWork配置/语言配置列表
    - name: order
      type: System.Int32
      value: 0
references:
- uid: Global
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: UnityEngine.Object
  commentId: T:UnityEngine.Object
  parent: UnityEngine
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: UnityEngine.Object
- uid: UnityEngine.ScriptableObject
  commentId: T:UnityEngine.ScriptableObject
  parent: UnityEngine
  isExternal: true
  name: ScriptableObject
  nameWithType: ScriptableObject
  fullName: UnityEngine.ScriptableObject
- uid: Global.BaseConfig{LanguageConfigItem}
  commentId: T:Global.BaseConfig{LanguageConfigItem}
  definition: Global.BaseConfig`1
  href: BaseConfig-1.html
  name: BaseConfig<LanguageConfigItem>
  nameWithType: BaseConfig<LanguageConfigItem>
  fullName: BaseConfig<LanguageConfigItem>
  nameWithType.vb: BaseConfig(Of LanguageConfigItem)
  fullName.vb: BaseConfig(Of LanguageConfigItem)
  name.vb: BaseConfig(Of LanguageConfigItem)
  spec.csharp:
  - uid: Global.BaseConfig`1
    name: BaseConfig
    href: BaseConfig-1.html
  - name: <
  - uid: Global.LanguageConfigItem
    name: LanguageConfigItem
    href: LanguageConfigItem.html
  - name: '>'
  spec.vb:
  - uid: Global.BaseConfig`1
    name: BaseConfig
    href: BaseConfig-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: Global.LanguageConfigItem
    name: LanguageConfigItem
    href: LanguageConfigItem.html
  - name: )
- uid: Global.BaseConfig{LanguageConfigItem}.version
  commentId: F:Global.BaseConfig{LanguageConfigItem}.version
  parent: Global.BaseConfig{LanguageConfigItem}
  definition: Global.BaseConfig`1.version
  href: Global.BaseConfig-1.html#BaseConfig_1_version
  name: version
  nameWithType: BaseConfig<LanguageConfigItem>.version
  fullName: BaseConfig<LanguageConfigItem>.version
  nameWithType.vb: BaseConfig(Of LanguageConfigItem).version
  fullName.vb: BaseConfig(Of LanguageConfigItem).version
- uid: Global.BaseConfig{LanguageConfigItem}.enableConsole
  commentId: F:Global.BaseConfig{LanguageConfigItem}.enableConsole
  parent: Global.BaseConfig{LanguageConfigItem}
  definition: Global.BaseConfig`1.enableConsole
  href: Global.BaseConfig-1.html#BaseConfig_1_enableConsole
  name: enableConsole
  nameWithType: BaseConfig<LanguageConfigItem>.enableConsole
  fullName: BaseConfig<LanguageConfigItem>.enableConsole
  nameWithType.vb: BaseConfig(Of LanguageConfigItem).enableConsole
  fullName.vb: BaseConfig(Of LanguageConfigItem).enableConsole
- uid: Global.BaseConfig{LanguageConfigItem}.dataList
  commentId: F:Global.BaseConfig{LanguageConfigItem}.dataList
  parent: Global.BaseConfig{LanguageConfigItem}
  definition: Global.BaseConfig`1.dataList
  href: Global.BaseConfig-1.html#BaseConfig_1_dataList
  name: dataList
  nameWithType: BaseConfig<LanguageConfigItem>.dataList
  fullName: BaseConfig<LanguageConfigItem>.dataList
  nameWithType.vb: BaseConfig(Of LanguageConfigItem).dataList
  fullName.vb: BaseConfig(Of LanguageConfigItem).dataList
- uid: Global.BaseConfig{LanguageConfigItem}.Item(System.Int32)
  commentId: P:Global.BaseConfig{LanguageConfigItem}.Item(System.Int32)
  parent: Global.BaseConfig{LanguageConfigItem}
  definition: Global.BaseConfig`1.Item(System.Int32)
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: this[int]
  nameWithType: BaseConfig<LanguageConfigItem>.this[int]
  fullName: BaseConfig<LanguageConfigItem>.this[int]
  nameWithType.vb: BaseConfig(Of LanguageConfigItem).this[](Integer)
  fullName.vb: BaseConfig(Of LanguageConfigItem).this[](Integer)
  name.vb: this[](Integer)
  spec.csharp:
  - name: this
  - name: '['
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: ']'
  spec.vb:
  - uid: Global.BaseConfig{LanguageConfigItem}.Item(System.Int32)
    name: this[]
    href: Global.BaseConfig-1.html#BaseConfig_1_Item_System_Int32_
  - name: (
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: Global.BaseConfig{LanguageConfigItem}.Item(System.String)
  commentId: P:Global.BaseConfig{LanguageConfigItem}.Item(System.String)
  parent: Global.BaseConfig{LanguageConfigItem}
  definition: Global.BaseConfig`1.Item(System.String)
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: this[string]
  nameWithType: BaseConfig<LanguageConfigItem>.this[string]
  fullName: BaseConfig<LanguageConfigItem>.this[string]
  nameWithType.vb: BaseConfig(Of LanguageConfigItem).this[](String)
  fullName.vb: BaseConfig(Of LanguageConfigItem).this[](String)
  name.vb: this[](String)
  spec.csharp:
  - name: this
  - name: '['
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ']'
  spec.vb:
  - uid: Global.BaseConfig{LanguageConfigItem}.Item(System.String)
    name: this[]
    href: Global.BaseConfig-1.html#BaseConfig_1_Item_System_String_
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: Global.BaseConfig{LanguageConfigItem}.DataCount
  commentId: P:Global.BaseConfig{LanguageConfigItem}.DataCount
  parent: Global.BaseConfig{LanguageConfigItem}
  definition: Global.BaseConfig`1.DataCount
  href: Global.BaseConfig-1.html#BaseConfig_1_DataCount
  name: DataCount
  nameWithType: BaseConfig<LanguageConfigItem>.DataCount
  fullName: BaseConfig<LanguageConfigItem>.DataCount
  nameWithType.vb: BaseConfig(Of LanguageConfigItem).DataCount
  fullName.vb: BaseConfig(Of LanguageConfigItem).DataCount
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: Global.BaseConfig`1
  commentId: T:Global.BaseConfig`1
  href: BaseConfig-1.html
  name: BaseConfig<T>
  nameWithType: BaseConfig<T>
  fullName: BaseConfig<T>
  nameWithType.vb: BaseConfig(Of T)
  fullName.vb: BaseConfig(Of T)
  name.vb: BaseConfig(Of T)
  spec.csharp:
  - uid: Global.BaseConfig`1
    name: BaseConfig
    href: BaseConfig-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Global.BaseConfig`1
    name: BaseConfig
    href: BaseConfig-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Global.BaseConfig`1.version
  commentId: F:Global.BaseConfig`1.version
  href: Global.BaseConfig-1.html#BaseConfig_1_version
  name: version
  nameWithType: BaseConfig<T>.version
  fullName: BaseConfig<T>.version
  nameWithType.vb: BaseConfig(Of T).version
  fullName.vb: BaseConfig(Of T).version
- uid: Global.BaseConfig`1.enableConsole
  commentId: F:Global.BaseConfig`1.enableConsole
  href: Global.BaseConfig-1.html#BaseConfig_1_enableConsole
  name: enableConsole
  nameWithType: BaseConfig<T>.enableConsole
  fullName: BaseConfig<T>.enableConsole
  nameWithType.vb: BaseConfig(Of T).enableConsole
  fullName.vb: BaseConfig(Of T).enableConsole
- uid: Global.BaseConfig`1.dataList
  commentId: F:Global.BaseConfig`1.dataList
  href: Global.BaseConfig-1.html#BaseConfig_1_dataList
  name: dataList
  nameWithType: BaseConfig<T>.dataList
  fullName: BaseConfig<T>.dataList
  nameWithType.vb: BaseConfig(Of T).dataList
  fullName.vb: BaseConfig(Of T).dataList
- uid: Global.BaseConfig`1.Item(System.Int32)
  commentId: P:Global.BaseConfig`1.Item(System.Int32)
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: this[int]
  nameWithType: BaseConfig<T>.this[int]
  fullName: BaseConfig<T>.this[int]
  nameWithType.vb: BaseConfig(Of T).this[](Integer)
  fullName.vb: BaseConfig(Of T).this[](Integer)
  name.vb: this[](Integer)
  spec.csharp:
  - name: this
  - name: '['
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: ']'
  spec.vb:
  - uid: Global.BaseConfig`1.Item(System.Int32)
    name: this[]
    href: Global.BaseConfig-1.html#BaseConfig_1_Item_System_Int32_
  - name: (
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: Global.BaseConfig`1.Item(System.String)
  commentId: P:Global.BaseConfig`1.Item(System.String)
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: this[string]
  nameWithType: BaseConfig<T>.this[string]
  fullName: BaseConfig<T>.this[string]
  nameWithType.vb: BaseConfig(Of T).this[](String)
  fullName.vb: BaseConfig(Of T).this[](String)
  name.vb: this[](String)
  spec.csharp:
  - name: this
  - name: '['
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ']'
  spec.vb:
  - uid: Global.BaseConfig`1.Item(System.String)
    name: this[]
    href: Global.BaseConfig-1.html#BaseConfig_1_Item_System_String_
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: Global.BaseConfig`1.DataCount
  commentId: P:Global.BaseConfig`1.DataCount
  href: Global.BaseConfig-1.html#BaseConfig_1_DataCount
  name: DataCount
  nameWithType: BaseConfig<T>.DataCount
  fullName: BaseConfig<T>.DataCount
  nameWithType.vb: BaseConfig(Of T).DataCount
  fullName.vb: BaseConfig(Of T).DataCount
