### YamlMime:ManagedReference
items:
- uid: Global.SkillsConfig
  commentId: T:Global.SkillsConfig
  id: SkillsConfig
  parent: Global
  children: []
  langs:
  - csharp
  - vb
  name: SkillsConfig
  nameWithType: SkillsConfig
  fullName: SkillsConfig
  type: Class
  source:
    remote:
      path: Assets/Scripts/Configs/SkillsConfig.cs
      branch: master
      repo: https://github.com/iiaa22/53-Unity.git
    id: SkillsConfig
    path: ../Assets/Scripts/Configs/SkillsConfig.cs
    startLine: 5
  assemblies:
  - Assembly-CSharp
  namespace: Global
  syntax:
    content: >-
      [CreateAssetMenu(fileName = "New SkillsConfig", menuName = "[YoJia]配置/技能配置列表", order = 0)]

      public class SkillsConfig : BaseConfig<SkillsConfigItem>
    content.vb: >-
      <CreateAssetMenu(fileName:="New SkillsConfig", menuName:="[YoJia]配置/技能配置列表", order:=0)>

      Public Class SkillsConfig Inherits BaseConfig(Of SkillsConfigItem)
  inheritance:
  - System.Object
  - UnityEngine.Object
  - UnityEngine.ScriptableObject
  - Global.BaseConfig{SkillsConfigItem}
  inheritedMembers:
  - Global.BaseConfig{SkillsConfigItem}.version
  - Global.BaseConfig{SkillsConfigItem}.enableConsole
  - Global.BaseConfig{SkillsConfigItem}.dataList
  - Global.BaseConfig{SkillsConfigItem}.Item(System.Int32)
  - Global.BaseConfig{SkillsConfigItem}.Item(System.String)
  - Global.BaseConfig{SkillsConfigItem}.DataCount
  attributes:
  - type: UnityEngine.CreateAssetMenuAttribute
    ctor: UnityEngine.CreateAssetMenuAttribute.#ctor
    arguments: []
    namedArguments:
    - name: fileName
      type: System.String
      value: New SkillsConfig
    - name: menuName
      type: System.String
      value: '[YoJia]配置/技能配置列表'
    - name: order
      type: System.Int32
      value: 0
references:
- uid: Global
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: UnityEngine.Object
  commentId: T:UnityEngine.Object
  parent: UnityEngine
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: UnityEngine.Object
- uid: UnityEngine.ScriptableObject
  commentId: T:UnityEngine.ScriptableObject
  parent: UnityEngine
  isExternal: true
  name: ScriptableObject
  nameWithType: ScriptableObject
  fullName: UnityEngine.ScriptableObject
- uid: Global.BaseConfig{SkillsConfigItem}
  commentId: T:Global.BaseConfig{SkillsConfigItem}
  definition: Global.BaseConfig`1
  href: BaseConfig-1.html
  name: BaseConfig<SkillsConfigItem>
  nameWithType: BaseConfig<SkillsConfigItem>
  fullName: BaseConfig<SkillsConfigItem>
  nameWithType.vb: BaseConfig(Of SkillsConfigItem)
  fullName.vb: BaseConfig(Of SkillsConfigItem)
  name.vb: BaseConfig(Of SkillsConfigItem)
  spec.csharp:
  - uid: Global.BaseConfig`1
    name: BaseConfig
    href: BaseConfig-1.html
  - name: <
  - uid: Global.SkillsConfigItem
    name: SkillsConfigItem
    href: SkillsConfigItem.html
  - name: '>'
  spec.vb:
  - uid: Global.BaseConfig`1
    name: BaseConfig
    href: BaseConfig-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: Global.SkillsConfigItem
    name: SkillsConfigItem
    href: SkillsConfigItem.html
  - name: )
- uid: Global.BaseConfig{SkillsConfigItem}.version
  commentId: F:Global.BaseConfig{SkillsConfigItem}.version
  parent: Global.BaseConfig{SkillsConfigItem}
  definition: Global.BaseConfig`1.version
  href: Global.BaseConfig-1.html#BaseConfig_1_version
  name: version
  nameWithType: BaseConfig<SkillsConfigItem>.version
  fullName: BaseConfig<SkillsConfigItem>.version
  nameWithType.vb: BaseConfig(Of SkillsConfigItem).version
  fullName.vb: BaseConfig(Of SkillsConfigItem).version
- uid: Global.BaseConfig{SkillsConfigItem}.enableConsole
  commentId: F:Global.BaseConfig{SkillsConfigItem}.enableConsole
  parent: Global.BaseConfig{SkillsConfigItem}
  definition: Global.BaseConfig`1.enableConsole
  href: Global.BaseConfig-1.html#BaseConfig_1_enableConsole
  name: enableConsole
  nameWithType: BaseConfig<SkillsConfigItem>.enableConsole
  fullName: BaseConfig<SkillsConfigItem>.enableConsole
  nameWithType.vb: BaseConfig(Of SkillsConfigItem).enableConsole
  fullName.vb: BaseConfig(Of SkillsConfigItem).enableConsole
- uid: Global.BaseConfig{SkillsConfigItem}.dataList
  commentId: F:Global.BaseConfig{SkillsConfigItem}.dataList
  parent: Global.BaseConfig{SkillsConfigItem}
  definition: Global.BaseConfig`1.dataList
  href: Global.BaseConfig-1.html#BaseConfig_1_dataList
  name: dataList
  nameWithType: BaseConfig<SkillsConfigItem>.dataList
  fullName: BaseConfig<SkillsConfigItem>.dataList
  nameWithType.vb: BaseConfig(Of SkillsConfigItem).dataList
  fullName.vb: BaseConfig(Of SkillsConfigItem).dataList
- uid: Global.BaseConfig{SkillsConfigItem}.Item(System.Int32)
  commentId: P:Global.BaseConfig{SkillsConfigItem}.Item(System.Int32)
  parent: Global.BaseConfig{SkillsConfigItem}
  definition: Global.BaseConfig`1.Item(System.Int32)
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: this[int]
  nameWithType: BaseConfig<SkillsConfigItem>.this[int]
  fullName: BaseConfig<SkillsConfigItem>.this[int]
  nameWithType.vb: BaseConfig(Of SkillsConfigItem).this[](Integer)
  fullName.vb: BaseConfig(Of SkillsConfigItem).this[](Integer)
  name.vb: this[](Integer)
  spec.csharp:
  - name: this
  - name: '['
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: ']'
  spec.vb:
  - uid: Global.BaseConfig{SkillsConfigItem}.Item(System.Int32)
    name: this[]
    href: Global.BaseConfig-1.html#BaseConfig_1_Item_System_Int32_
  - name: (
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: Global.BaseConfig{SkillsConfigItem}.Item(System.String)
  commentId: P:Global.BaseConfig{SkillsConfigItem}.Item(System.String)
  parent: Global.BaseConfig{SkillsConfigItem}
  definition: Global.BaseConfig`1.Item(System.String)
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: this[string]
  nameWithType: BaseConfig<SkillsConfigItem>.this[string]
  fullName: BaseConfig<SkillsConfigItem>.this[string]
  nameWithType.vb: BaseConfig(Of SkillsConfigItem).this[](String)
  fullName.vb: BaseConfig(Of SkillsConfigItem).this[](String)
  name.vb: this[](String)
  spec.csharp:
  - name: this
  - name: '['
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ']'
  spec.vb:
  - uid: Global.BaseConfig{SkillsConfigItem}.Item(System.String)
    name: this[]
    href: Global.BaseConfig-1.html#BaseConfig_1_Item_System_String_
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: Global.BaseConfig{SkillsConfigItem}.DataCount
  commentId: P:Global.BaseConfig{SkillsConfigItem}.DataCount
  parent: Global.BaseConfig{SkillsConfigItem}
  definition: Global.BaseConfig`1.DataCount
  href: Global.BaseConfig-1.html#BaseConfig_1_DataCount
  name: DataCount
  nameWithType: BaseConfig<SkillsConfigItem>.DataCount
  fullName: BaseConfig<SkillsConfigItem>.DataCount
  nameWithType.vb: BaseConfig(Of SkillsConfigItem).DataCount
  fullName.vb: BaseConfig(Of SkillsConfigItem).DataCount
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: Global.BaseConfig`1
  commentId: T:Global.BaseConfig`1
  href: BaseConfig-1.html
  name: BaseConfig<T>
  nameWithType: BaseConfig<T>
  fullName: BaseConfig<T>
  nameWithType.vb: BaseConfig(Of T)
  fullName.vb: BaseConfig(Of T)
  name.vb: BaseConfig(Of T)
  spec.csharp:
  - uid: Global.BaseConfig`1
    name: BaseConfig
    href: BaseConfig-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Global.BaseConfig`1
    name: BaseConfig
    href: BaseConfig-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Global.BaseConfig`1.version
  commentId: F:Global.BaseConfig`1.version
  href: Global.BaseConfig-1.html#BaseConfig_1_version
  name: version
  nameWithType: BaseConfig<T>.version
  fullName: BaseConfig<T>.version
  nameWithType.vb: BaseConfig(Of T).version
  fullName.vb: BaseConfig(Of T).version
- uid: Global.BaseConfig`1.enableConsole
  commentId: F:Global.BaseConfig`1.enableConsole
  href: Global.BaseConfig-1.html#BaseConfig_1_enableConsole
  name: enableConsole
  nameWithType: BaseConfig<T>.enableConsole
  fullName: BaseConfig<T>.enableConsole
  nameWithType.vb: BaseConfig(Of T).enableConsole
  fullName.vb: BaseConfig(Of T).enableConsole
- uid: Global.BaseConfig`1.dataList
  commentId: F:Global.BaseConfig`1.dataList
  href: Global.BaseConfig-1.html#BaseConfig_1_dataList
  name: dataList
  nameWithType: BaseConfig<T>.dataList
  fullName: BaseConfig<T>.dataList
  nameWithType.vb: BaseConfig(Of T).dataList
  fullName.vb: BaseConfig(Of T).dataList
- uid: Global.BaseConfig`1.Item(System.Int32)
  commentId: P:Global.BaseConfig`1.Item(System.Int32)
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: this[int]
  nameWithType: BaseConfig<T>.this[int]
  fullName: BaseConfig<T>.this[int]
  nameWithType.vb: BaseConfig(Of T).this[](Integer)
  fullName.vb: BaseConfig(Of T).this[](Integer)
  name.vb: this[](Integer)
  spec.csharp:
  - name: this
  - name: '['
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: ']'
  spec.vb:
  - uid: Global.BaseConfig`1.Item(System.Int32)
    name: this[]
    href: Global.BaseConfig-1.html#BaseConfig_1_Item_System_Int32_
  - name: (
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: Global.BaseConfig`1.Item(System.String)
  commentId: P:Global.BaseConfig`1.Item(System.String)
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: this[string]
  nameWithType: BaseConfig<T>.this[string]
  fullName: BaseConfig<T>.this[string]
  nameWithType.vb: BaseConfig(Of T).this[](String)
  fullName.vb: BaseConfig(Of T).this[](String)
  name.vb: this[](String)
  spec.csharp:
  - name: this
  - name: '['
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ']'
  spec.vb:
  - uid: Global.BaseConfig`1.Item(System.String)
    name: this[]
    href: Global.BaseConfig-1.html#BaseConfig_1_Item_System_String_
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: Global.BaseConfig`1.DataCount
  commentId: P:Global.BaseConfig`1.DataCount
  href: Global.BaseConfig-1.html#BaseConfig_1_DataCount
  name: DataCount
  nameWithType: BaseConfig<T>.DataCount
  fullName: BaseConfig<T>.DataCount
  nameWithType.vb: BaseConfig(Of T).DataCount
  fullName.vb: BaseConfig(Of T).DataCount
