### YamlMime:ManagedReference
items:
- uid: Global.StatesConfig
  commentId: T:Global.StatesConfig
  id: StatesConfig
  parent: Global
  children: []
  langs:
  - csharp
  - vb
  name: StatesConfig
  nameWithType: StatesConfig
  fullName: StatesConfig
  type: Class
  source:
    remote:
      path: Assets/Scripts/Configs/StatesConfig.cs
      branch: master
      repo: https://github.com/iiaa22/53-Unity.git
    id: StatesConfig
    path: ../Assets/Scripts/Configs/StatesConfig.cs
    startLine: 5
  assemblies:
  - Assembly-CSharp
  namespace: Global
  syntax:
    content: >-
      [CreateAssetMenu(fileName = "New StatesConfig", menuName = "[YoJia]配置/状态配置列表", order = 0)]

      public class StatesConfig : BaseConfig<StatesConfigItem>
    content.vb: >-
      <CreateAssetMenu(fileName:="New StatesConfig", menuName:="[YoJia]配置/状态配置列表", order:=0)>

      Public Class StatesConfig Inherits BaseConfig(Of StatesConfigItem)
  inheritance:
  - System.Object
  - UnityEngine.Object
  - UnityEngine.ScriptableObject
  - Global.BaseConfig{StatesConfigItem}
  inheritedMembers:
  - Global.BaseConfig{StatesConfigItem}.version
  - Global.BaseConfig{StatesConfigItem}.enableConsole
  - Global.BaseConfig{StatesConfigItem}.dataList
  - Global.BaseConfig{StatesConfigItem}.Item(System.Int32)
  - Global.BaseConfig{StatesConfigItem}.Item(System.String)
  - Global.BaseConfig{StatesConfigItem}.DataCount
  attributes:
  - type: UnityEngine.CreateAssetMenuAttribute
    ctor: UnityEngine.CreateAssetMenuAttribute.#ctor
    arguments: []
    namedArguments:
    - name: fileName
      type: System.String
      value: New StatesConfig
    - name: menuName
      type: System.String
      value: '[YoJia]配置/状态配置列表'
    - name: order
      type: System.Int32
      value: 0
references:
- uid: Global
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: UnityEngine.Object
  commentId: T:UnityEngine.Object
  parent: UnityEngine
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: UnityEngine.Object
- uid: UnityEngine.ScriptableObject
  commentId: T:UnityEngine.ScriptableObject
  parent: UnityEngine
  isExternal: true
  name: ScriptableObject
  nameWithType: ScriptableObject
  fullName: UnityEngine.ScriptableObject
- uid: Global.BaseConfig{StatesConfigItem}
  commentId: T:Global.BaseConfig{StatesConfigItem}
  definition: Global.BaseConfig`1
  href: BaseConfig-1.html
  name: BaseConfig<StatesConfigItem>
  nameWithType: BaseConfig<StatesConfigItem>
  fullName: BaseConfig<StatesConfigItem>
  nameWithType.vb: BaseConfig(Of StatesConfigItem)
  fullName.vb: BaseConfig(Of StatesConfigItem)
  name.vb: BaseConfig(Of StatesConfigItem)
  spec.csharp:
  - uid: Global.BaseConfig`1
    name: BaseConfig
    href: BaseConfig-1.html
  - name: <
  - uid: Global.StatesConfigItem
    name: StatesConfigItem
    href: StatesConfigItem.html
  - name: '>'
  spec.vb:
  - uid: Global.BaseConfig`1
    name: BaseConfig
    href: BaseConfig-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: Global.StatesConfigItem
    name: StatesConfigItem
    href: StatesConfigItem.html
  - name: )
- uid: Global.BaseConfig{StatesConfigItem}.version
  commentId: F:Global.BaseConfig{StatesConfigItem}.version
  parent: Global.BaseConfig{StatesConfigItem}
  definition: Global.BaseConfig`1.version
  href: Global.BaseConfig-1.html#BaseConfig_1_version
  name: version
  nameWithType: BaseConfig<StatesConfigItem>.version
  fullName: BaseConfig<StatesConfigItem>.version
  nameWithType.vb: BaseConfig(Of StatesConfigItem).version
  fullName.vb: BaseConfig(Of StatesConfigItem).version
- uid: Global.BaseConfig{StatesConfigItem}.enableConsole
  commentId: F:Global.BaseConfig{StatesConfigItem}.enableConsole
  parent: Global.BaseConfig{StatesConfigItem}
  definition: Global.BaseConfig`1.enableConsole
  href: Global.BaseConfig-1.html#BaseConfig_1_enableConsole
  name: enableConsole
  nameWithType: BaseConfig<StatesConfigItem>.enableConsole
  fullName: BaseConfig<StatesConfigItem>.enableConsole
  nameWithType.vb: BaseConfig(Of StatesConfigItem).enableConsole
  fullName.vb: BaseConfig(Of StatesConfigItem).enableConsole
- uid: Global.BaseConfig{StatesConfigItem}.dataList
  commentId: F:Global.BaseConfig{StatesConfigItem}.dataList
  parent: Global.BaseConfig{StatesConfigItem}
  definition: Global.BaseConfig`1.dataList
  href: Global.BaseConfig-1.html#BaseConfig_1_dataList
  name: dataList
  nameWithType: BaseConfig<StatesConfigItem>.dataList
  fullName: BaseConfig<StatesConfigItem>.dataList
  nameWithType.vb: BaseConfig(Of StatesConfigItem).dataList
  fullName.vb: BaseConfig(Of StatesConfigItem).dataList
- uid: Global.BaseConfig{StatesConfigItem}.Item(System.Int32)
  commentId: P:Global.BaseConfig{StatesConfigItem}.Item(System.Int32)
  parent: Global.BaseConfig{StatesConfigItem}
  definition: Global.BaseConfig`1.Item(System.Int32)
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: this[int]
  nameWithType: BaseConfig<StatesConfigItem>.this[int]
  fullName: BaseConfig<StatesConfigItem>.this[int]
  nameWithType.vb: BaseConfig(Of StatesConfigItem).this[](Integer)
  fullName.vb: BaseConfig(Of StatesConfigItem).this[](Integer)
  name.vb: this[](Integer)
  spec.csharp:
  - name: this
  - name: '['
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: ']'
  spec.vb:
  - uid: Global.BaseConfig{StatesConfigItem}.Item(System.Int32)
    name: this[]
    href: Global.BaseConfig-1.html#BaseConfig_1_Item_System_Int32_
  - name: (
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: Global.BaseConfig{StatesConfigItem}.Item(System.String)
  commentId: P:Global.BaseConfig{StatesConfigItem}.Item(System.String)
  parent: Global.BaseConfig{StatesConfigItem}
  definition: Global.BaseConfig`1.Item(System.String)
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: this[string]
  nameWithType: BaseConfig<StatesConfigItem>.this[string]
  fullName: BaseConfig<StatesConfigItem>.this[string]
  nameWithType.vb: BaseConfig(Of StatesConfigItem).this[](String)
  fullName.vb: BaseConfig(Of StatesConfigItem).this[](String)
  name.vb: this[](String)
  spec.csharp:
  - name: this
  - name: '['
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ']'
  spec.vb:
  - uid: Global.BaseConfig{StatesConfigItem}.Item(System.String)
    name: this[]
    href: Global.BaseConfig-1.html#BaseConfig_1_Item_System_String_
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: Global.BaseConfig{StatesConfigItem}.DataCount
  commentId: P:Global.BaseConfig{StatesConfigItem}.DataCount
  parent: Global.BaseConfig{StatesConfigItem}
  definition: Global.BaseConfig`1.DataCount
  href: Global.BaseConfig-1.html#BaseConfig_1_DataCount
  name: DataCount
  nameWithType: BaseConfig<StatesConfigItem>.DataCount
  fullName: BaseConfig<StatesConfigItem>.DataCount
  nameWithType.vb: BaseConfig(Of StatesConfigItem).DataCount
  fullName.vb: BaseConfig(Of StatesConfigItem).DataCount
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: Global.BaseConfig`1
  commentId: T:Global.BaseConfig`1
  href: BaseConfig-1.html
  name: BaseConfig<T>
  nameWithType: BaseConfig<T>
  fullName: BaseConfig<T>
  nameWithType.vb: BaseConfig(Of T)
  fullName.vb: BaseConfig(Of T)
  name.vb: BaseConfig(Of T)
  spec.csharp:
  - uid: Global.BaseConfig`1
    name: BaseConfig
    href: BaseConfig-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Global.BaseConfig`1
    name: BaseConfig
    href: BaseConfig-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Global.BaseConfig`1.version
  commentId: F:Global.BaseConfig`1.version
  href: Global.BaseConfig-1.html#BaseConfig_1_version
  name: version
  nameWithType: BaseConfig<T>.version
  fullName: BaseConfig<T>.version
  nameWithType.vb: BaseConfig(Of T).version
  fullName.vb: BaseConfig(Of T).version
- uid: Global.BaseConfig`1.enableConsole
  commentId: F:Global.BaseConfig`1.enableConsole
  href: Global.BaseConfig-1.html#BaseConfig_1_enableConsole
  name: enableConsole
  nameWithType: BaseConfig<T>.enableConsole
  fullName: BaseConfig<T>.enableConsole
  nameWithType.vb: BaseConfig(Of T).enableConsole
  fullName.vb: BaseConfig(Of T).enableConsole
- uid: Global.BaseConfig`1.dataList
  commentId: F:Global.BaseConfig`1.dataList
  href: Global.BaseConfig-1.html#BaseConfig_1_dataList
  name: dataList
  nameWithType: BaseConfig<T>.dataList
  fullName: BaseConfig<T>.dataList
  nameWithType.vb: BaseConfig(Of T).dataList
  fullName.vb: BaseConfig(Of T).dataList
- uid: Global.BaseConfig`1.Item(System.Int32)
  commentId: P:Global.BaseConfig`1.Item(System.Int32)
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: this[int]
  nameWithType: BaseConfig<T>.this[int]
  fullName: BaseConfig<T>.this[int]
  nameWithType.vb: BaseConfig(Of T).this[](Integer)
  fullName.vb: BaseConfig(Of T).this[](Integer)
  name.vb: this[](Integer)
  spec.csharp:
  - name: this
  - name: '['
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: ']'
  spec.vb:
  - uid: Global.BaseConfig`1.Item(System.Int32)
    name: this[]
    href: Global.BaseConfig-1.html#BaseConfig_1_Item_System_Int32_
  - name: (
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: Global.BaseConfig`1.Item(System.String)
  commentId: P:Global.BaseConfig`1.Item(System.String)
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: this[string]
  nameWithType: BaseConfig<T>.this[string]
  fullName: BaseConfig<T>.this[string]
  nameWithType.vb: BaseConfig(Of T).this[](String)
  fullName.vb: BaseConfig(Of T).this[](String)
  name.vb: this[](String)
  spec.csharp:
  - name: this
  - name: '['
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ']'
  spec.vb:
  - uid: Global.BaseConfig`1.Item(System.String)
    name: this[]
    href: Global.BaseConfig-1.html#BaseConfig_1_Item_System_String_
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: Global.BaseConfig`1.DataCount
  commentId: P:Global.BaseConfig`1.DataCount
  href: Global.BaseConfig-1.html#BaseConfig_1_DataCount
  name: DataCount
  nameWithType: BaseConfig<T>.DataCount
  fullName: BaseConfig<T>.DataCount
  nameWithType.vb: BaseConfig(Of T).DataCount
  fullName.vb: BaseConfig(Of T).DataCount
